global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "anomaly_service"
    static_configs:
      - targets: ["consumer:8000"]

  - job_name: "redis_exporter"
    static_configs:
      - targets: ["redis_exporter:9121"]

  # Add Redis exporter here if you deploy one
